### ISSUE TITLE
During normal autosummary use (not relevant to fixtures), sphinx_autofixture crashes when a dataclass is present

### ISSUE THREAD

**Issue by xuhdev** [sphinx-toolbox/sphinx-autofixture#6]
## Description

When applying autosummary to a dataclass, sphinx_autofixture crashes.

## Steps to Reproduce

1. Download [bug.tar.gz](https://github.com/sphinx-toolbox/sphinx-autofixture/files/5763194/bug.tar.gz).
2. Run `pip install sphinx-autofixture`.
2. Run `PYTHONPATH=. sphinx-build -v -d "./_build" docs "_build/html" -b html -W --color`

bug.tar.gz:

```
├── docs
│   ├── conf.py
│   └── index.rst
└── myproject.py
```

`index.rst`:

```rst
Welcome to myproject's documentation!
=====================================

.. currentmodule:: myproject

.. autosummary::
   :toctree:

   A
```

`conf.py`:

```python
project = 'myproject'
copyright = '2020, someone'
author = 'someone'
extensions = [
    'sphinx.ext.autosummary',
    'sphinx_autofixture'
]
html_theme = 'alabaster'

autosummary_generate = True
```

`myproject.py`:

```python
from dataclasses import dataclass

@dataclass(frozen=True)
class A:
    "A class."
```

## Actual result:

```
...
[app] connecting event 'config-inited' (500): <function validate_config at 0x7fe2f6934400> [id=62]
making output directory... done
[app] emitting event: 'config-inited'(<sphinx.config.Config object at 0x7fe2f72be7f0>,)
[app] emitting event: 'builder-inited'()
[autosummary] generating autosummary for: index.rst

Traceback (most recent call last):
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py", line 806, in process_generate_options
    encoding=app.config.source_encoding)
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/ext/autosummary/generate.py", line 430, in generate_autosummary_docs
    modname, qualname)
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/ext/autosummary/generate.py", line 320, in generate_autosummary_content
    get_members(obj, {'method'}, ['__init__'])
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/ext/autosummary/generate.py", line 257, in get_members
    documenter = get_documenter(app, value, obj)
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py", line 210, in get_documenter
    classes = [cls for cls in app.registry.documenters.values()
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py", line 211, in <listcomp>
    if cls.can_document_member(obj, '', False, parent_doc)]
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx_autofixture/__init__.py", line 152, in can_document_member
    return is_fixture(member)[0]
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx_autofixture/__init__.py", line 109, in is_fixture
    visitor.visit(ast.parse(inspect.getsource(function)))
  File "/usr/lib/python3.7/inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/application.py", line 278, in __init__
    self._init_builder()
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/application.py", line 337, in _init_builder
    self.events.emit('builder-inited')
  File "/home/hong/tmp/.venv/lib/python3.7/site-packages/sphinx/events.py", line 118, in emit
    (listener.handler, name), exc) from exc
sphinx.errors.ExtensionError: Handler <function process_generate_options at 0x7fe2f699b840> for event 'builder-inited' threw an exception (exception: could not get source code)

Extension error:
Handler <function process_generate_options at 0x7fe2f699b840> for event 'builder-inited' threw an exception (exception: could not get source code)
```

Removing `sphinx_autofixture` from the list of extensions stops the crash.

## Expected result:

No crash.

## Version

  * Operating System: Debian 10
  * Python: 3.7.3
  * sphinx-autofixture: 0.2.2

## Installation source

PyPI

**Comment by domdfcoding** [comment]
Hi @xuhdev,

Apologies for not looking at this sooner. I have found the issue - the way dataclasses generate their code means that `inspect.getsource` can't find it, causing the crash.

I believe I have now fixed it. Can you try the [issue-6](https://github.com/sphinx-toolbox/sphinx-autofixture/tree/issue-6) branch, which you can install with:

```console
python3 -m pip install git+https://github.com/sphinx-toolbox/sphinx-autofixture/@issue-6 --force-reinstall --no-deps
```

If you're using a recent version of `pip` you'll need the ` --force-reinstall --no-deps` flags.


Let my know if that fixes it for you, and if it does I will release the fix to PyPI.

**Comment by xuhdev** [comment]
Thanks for the fix! It works now.

**Comment by domdfcoding** [comment]
Wonderful. I will publish a new release to PyPI
